# This is Cloud-Installer template of Websoft9
# Task priority: pre_tasks > role > tasks > post_task
# Variable priority: vars_files > vars

- name: Alldocs
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_cloud, tags: "role_cloud"}  
    - {role: role_nodejs, tags: "role_nodejs"}  
    - {role: alldocs, tags: "alldocs"}
    - {role: role_preend, tags: "preend"}
    - {role: role_end, tags: "role_end"}
