#2 Install
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Install vuepress
  shell: npm install -g vuepress

- name: Install vuepress
  shell: mkdir docs
  args:
    chdir: /data

- name: Clone all  Repositories of ansible
  shell: | 
   git clone https://github.com/Websoft9/ansible-{{item}}.git
   cd /data/ansible-{{item}}/docs
   vuepress build
   cp -R /data/ansible-{{item}}/docs/html/{{item}} /data/docs/
  register: gitclone_result
  failed_when: False
  loop: "{{ alldocs_repolist }}" 
  args:
    chdir: /data

- debug: 
    msg: "{{ gitclone_result | json_query('results[*].results[*]') }}"